version: 1.1

stages:
  - stage:
    - git-checkout:

  - stage:
    - java:
        alias: bp-demo
        params:
          build_type: maven
          workdir: ${git-checkout}
          target: ./demo-server/target/demo-server-0.0.1-SNAPSHOT.jar
          container_type: spring-boot

  - stage:
      - release:
          params:
            dice_yml: ${git-checkout}/dice.yml
            image:
              demo: ${bp-demo:OUTPUT:image}

  - stage:
      - dice:
          params:
            release_id_path: ${release}