spring:
  profiles:
    include: >
      trantor

trantor:
  module:
    name: @project.name@
    description: @project.description@
    version: @project.version@
    classify: RE_DEVELOP
    scan-package: io.terminus.trantor.demo.custom

server:
  address: 0.0.0.0
  port: 8081

logging:
  level:
    io.terminus.platform.sdk.dao: debug
