server:
  address: 0.0.0.0
  port: 8081

logging:
  level:
    io.terminus.platform.sdk.dao: debug

spring:
  profiles:
    include: >
      trantor

trantor:
  module:
    name: @project.name@
    description: @project.description@
    version: @project.version@
    classify: PRODUCT
    scan-package: io.terminus.trantor.demo.user
#  dalaran:
#    runtimeUrl: https://runtime-dev-7672.app.terminus.io/
#    consoleUrl: https://dev-dalaran-api.app.terminus.io/
