spring:
  profiles:
    include: >
      trantor

logging:
  level:
    io.terminus.platform.sdk.dao: debug

trantor:
  module:
    name: @project.name@
    description: @project.description@
    version: @project.version@
    classify: PRODUCT
    scan-package: io.terminus.trantor.demo.item
